"""Hyperparameter search over pipeline configurations.

Defines a framework-agnostic search framework that trains a :class:`BasePipeline`
subclass across many configurations and reports the best one. Two concrete
strategies are provided:

    - :class:`GridSearch` — exhaustive Cartesian product over a parameter grid.
    - :class:`RandomSearch` — random sampling without replacement from a grid.

Each trial constructs a fresh pipeline via ``pipeline_cls(config)``, runs it in
train mode, and scores it with the metric named by ``scoring``. Trial failures
are caught, logged, and skipped rather than aborting the whole search.
"""

from __future__ import annotations

import itertools
import logging
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from copy import deepcopy
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np

if TYPE_CHECKING:
    from pipeline.config import Config

_logger = logging.getLogger(__name__)


@dataclass
class TrialResult:
    """Outcome of one hyperparameter trial.

    Attributes:
        trial_id: Zero-based index of the trial.
        config: The configuration that was evaluated.
        metrics: Metric values computed during evaluation.
        score: The scalar score extracted from ``metrics[self.scoring]``.
            ``None`` if the trial failed or the metric was missing.
    """

    trial_id: int
    config: Any
    metrics: dict[str, float] = field(default_factory=dict)
    score: float | None = None


@dataclass
class SearchResult:
    """Aggregated outcome of a hyperparameter search.

    Attributes:
        trials: Every trial attempted, oldest first. Failed trials have a
            ``None`` score.
        scoring: The metric used to rank trials.
    """

    trials: list[TrialResult]
    scoring: str

    @property
    def best_trial(self) -> TrialResult | None:
        """The highest-scoring trial, or None if no trial succeeded."""
        succeeded = [t for t in self.trials if t.score is not None]
        if not succeeded:
            return None
        return max(succeeded, key=lambda t: t.score)

    @property
    def best_config(self) -> Any | None:
        """The configuration of the best trial, or None if none succeeded."""
        best = self.best_trial
        return best.config if best else None

    @property
    def best_score(self) -> float | None:
        """The score of the best trial, or None if none succeeded."""
        best = self.best_trial
        return best.score if best else None

    def to_dataframe(self) -> Any:
        """Return a pandas DataFrame of one row per trial.

        Columns are ``trial_id``, ``score``, plus every distinct config key
        seen across trials. Failed trials carry a ``None`` score.

        Returns:
            A pandas ``DataFrame``.

        Raises:
            ImportError: If pandas is not installed.
        """
        from dataclasses import asdict, is_dataclass

        import pandas as pd

        rows: list[dict[str, Any]] = []
        for trial in self.trials:
            row: dict[str, Any] = {
                "trial_id": trial.trial_id,
                "score": trial.score,
            }
            if isinstance(trial.config, Mapping):
                fields = dict(trial.config)
            elif is_dataclass(trial.config):
                fields = asdict(trial.config)
            else:
                fields = {}
            row.update(fields)
            rows.append(row)

        df = pd.DataFrame(rows)
        if df.empty:
            df = pd.DataFrame(columns=["trial_id", "score"])
        return df


class BaseSearch(ABC):
    """Abstract strategy for searching over hyperparameter configurations.

    Subclasses implement :meth:`_generate_configs` to produce candidate
    configurations. The shared :meth:`run` trains a fresh pipeline per
    candidate, scores it, and collects the results.

    Parameters:
        pipeline_cls: A :class:`BasePipeline` subclass constructible from a
            single ``config`` argument.
        base_config: The starting configuration. Every candidate is a copy of
            this with specific fields overridden.
        scoring: The metric name to optimize (e.g. ``"accuracy"``). Read from
            ``state.metrics[self.scoring]`` after each run.
    """

    def __init__(self, pipeline_cls: type, base_config: Config, scoring: str) -> None:
        self.pipeline_cls = pipeline_cls
        self.base_config = base_config
        self.scoring = scoring

    def run(self) -> SearchResult:
        """Train one pipeline per candidate config and rank the results.

        For each config generated by :meth:`_generate_configs`, a fresh
        pipeline is constructed and run in train mode. The score is read
        from ``state.metrics[self.scoring]``. Trials that raise during
        training are logged and skipped (their score stays ``None``).

        Returns:
            A :class:`SearchResult` containing every attempted trial.
        """
        trials: list[TrialResult] = []
        for trial_id, config in enumerate(self._generate_configs()):
            trial = self._run_trial(trial_id, config)
            trials.append(trial)
        return SearchResult(trials=trials, scoring=self.scoring)

    def _run_trial(self, trial_id: int, config: Config) -> TrialResult:
        """Train and score one configuration, guarding against failures.

        Args:
            trial_id: Zero-based index assigned to this trial.
            config: The configuration to evaluate.

        Returns:
            A :class:`TrialResult` with the computed score, or a ``None`` score
            if the trial failed.
        """
        try:
            pipeline = self.pipeline_cls(config)
            state = pipeline.run("train")
            metrics: dict[str, float] = {
                name: state.metrics[name] for name in state.metrics
            }
            score = metrics[self.scoring]
            return TrialResult(trial_id=trial_id, config=config, metrics=metrics, score=score)
        except Exception:  # noqa: BLE001 - a failing config must not kill the search
            _logger.warning("Trial %d failed with config %s", trial_id, config, exc_info=True)
            return TrialResult(trial_id=trial_id, config=config, score=None)

    @abstractmethod
    def _generate_configs(self):
        """Yield one configuration per candidate to evaluate.

        Subclasses override this. Each yielded object becomes the config for
        one trial and is passed to ``self.pipeline_cls(config)``.
        """
        ...


class GridSearch(BaseSearch):
    """Exhaustively evaluate the Cartesian product of a parameter grid.

    The grid maps each hyperparameter name to a sequence of candidate values.
    Every combination of one value per parameter is evaluated exactly once.

    Parameters:
        param_grid: ``{name: [value, ...]}``. Must be non-empty and each key
            should match an attribute on the base config.
        kwargs: Forwarded to :class:`BaseSearch`.
    """

    def __init__(self, param_grid: Mapping[str, Sequence[Any]], **kwargs: Any) -> None:
        if not param_grid:
            raise ValueError("param_grid must contain at least one hyperparameter")
        super().__init__(**kwargs)
        self.param_grid = param_grid
        self._keys = list(param_grid.keys())

    def _generate_configs(self):
        """Yield the Cartesian product of the parameter grid."""
        for combo in itertools.product(*(self.param_grid[k] for k in self._keys)):
            yield self._config_from_combo(dict(zip(self._keys, combo, strict=True)))

    def _config_from_combo(self, combo: Mapping[str, Any]) -> Config:
        """Build a config copy with each ``combo`` field set via setattr."""
        config = deepcopy(self.base_config)
        for key, value in combo.items():
            setattr(config, key, value)
        return config


class RandomSearch(BaseSearch):
    """Randomly sample configurations from a grid without replacement.

    One random value is drawn from each grid column per trial; combinations are
    sampled without replacement. If ``n_trials`` exceeds the total number of
    distinct combinations, the sample is clamped to that total.

    Parameters:
        param_grid: ``{name: [value, ...]}`` defining the search space.
        n_trials: Number of configurations to sample. Clamped to the total
            number of distinct combinations if it exceeds them.
        seed: Seed for reproducibility.
        kwargs: Forwarded to :class:`BaseSearch`.
    """

    def __init__(
        self,
        param_grid: Mapping[str, Sequence[Any]],
        n_trials: int,
        seed: int,
        **kwargs: Any,
    ) -> None:
        if not param_grid:
            raise ValueError("param_grid must contain at least one hyperparameter")
        if n_trials < 1:
            raise ValueError("n_trials must be a positive integer")
        super().__init__(**kwargs)
        self.param_grid = param_grid
        self._n_trials = n_trials
        self._seed = seed

    def _total_combinations(self) -> int:
        """The number of distinct combinations in the grid."""
        total = 1
        for values in self.param_grid.values():
            total *= len(values)
        return total

    def _generate_configs(self):
        """Yield sampled configurations without replacement."""
        keys = list(self.param_grid.keys())
        total = self._total_combinations()
        n = min(self._n_trials, total)

        rng = np.random.default_rng(self._seed)
        for flat_idx in rng.choice(total, size=n, replace=False):
            yield self._config_from_flat(keys, flat_idx)

    def _config_from_flat(self, keys: list[str], flat_idx: int) -> Config:
        """Unpack a flat lexicographic index into a config copy.

        Maps ``flat_idx`` (0 .. total-1) to a distinct combination using the
        same ordering as :func:`itertools.product`: the last key varies the
        fastest.
        """
        stride = self._total_combinations()
        combo: dict[str, Any] = {}
        for key in keys:
            stride //= len(self.param_grid[key])
            value = self.param_grid[key][(flat_idx // stride) % len(self.param_grid[key])]
            combo[key] = value
        return self._apply_combo(combo)

    def _apply_combo(self, combo: Mapping[str, Any]) -> Config:
        """Build a config copy with each ``combo`` field set via setattr."""
        config = deepcopy(self.base_config)
        for key, value in combo.items():
            setattr(config, key, value)
        return config
